apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-ds
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: default
      host: clickhouse
      port: 8123
      protocol: http
      username: default
    editable: false
